"""initial_migration

Revision ID: 89cd421d6566
Revises: 
Create Date: 2026-05-23 20:03:40.554666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89cd421d6566'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('jp_factor', sa.Float(), nullable=False),
    sa.Column('sp_factor', sa.Float(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    op.create_table('draws',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('open_date', sa.DateTime(), nullable=False),
    sa.Column('cutoff_time', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('house_holding_amount', sa.Float(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draws_id'), 'draws', ['id'], unique=False)
    op.create_table('master_dealers',
    sa.Column('id', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('jp_factor', sa.Float(), nullable=False),
    sa.Column('sp_factor', sa.Float(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_dealers_id'), 'master_dealers', ['id'], unique=False)
    
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draw_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=3), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['draw_id'], ['draws.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_id'), 'batches', ['id'], unique=False)
    op.create_table('offloaded',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draw_id', sa.Integer(), nullable=False),
    sa.Column('master_dealer_id', sa.String(length=3), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('ticket', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['draw_id'], ['draws.id'], ),
    sa.ForeignKeyConstraint(['master_dealer_id'], ['master_dealers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offloaded_id'), 'offloaded', ['id'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draw_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=3), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('ticket', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['draw_id'], ['draws.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_id'), 'sales', ['id'], unique=False)

    # Manual view creation
    op.execute("""
        CREATE VIEW sales_by_ticket_per_draw AS
        SELECT draw_id, ticket, SUM(amount) as total_amount
        FROM sales
        GROUP BY draw_id, ticket;
    """)
    op.execute("""
        CREATE VIEW offloaded_amount_by_ticket_per_draw AS
        SELECT draw_id, ticket, SUM(amount) as total_offloaded
        FROM offloaded
        GROUP BY draw_id, ticket;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS sales_by_ticket_per_draw")
    op.execute("DROP VIEW IF EXISTS offloaded_amount_by_ticket_per_draw")
    
    op.drop_index(op.f('ix_sales_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_offloaded_id'), table_name='offloaded')
    op.drop_table('offloaded')
    op.drop_index(op.f('ix_batches_id'), table_name='batches')
    op.drop_table('batches')
    op.drop_index(op.f('ix_master_dealers_id'), table_name='master_dealers')
    op.drop_table('master_dealers')
    op.drop_index(op.f('ix_draws_id'), table_name='draws')
    op.drop_table('draws')
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
